import Head from "next/head";
import Image from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useSelector, useDispatch } from "react-redux";
import { updateState } from "../../redux/features/testSlice";
const inter = Inter({ subsets: ["latin"] });

export default function Home() {
  // const { test } = useSelector((state) => state.)
const teststate = useSelector((state) => state.testSlice.test);
  const dispatch = useDispatch();

  const update = () => {
    dispatch(updateState("hello"));
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main>
        <button onClick={update}>update</button>

        {
          teststate
        }
      </main>
    </>
  );
}
